### ISSUE TITLE
PHP warning caused by duplicate property definition

### ISSUE THREAD

**Issue by gyula-szabo** [kartik-v/yii2-widget-fileinput#140]
Hello there!

The latest version of yii2-krajee-base breaks the file input widget under PHP 5.6.

## Steps to reproduce the issue

1. Update yii2-krajee-base to latest release
2. Try to use the file input widget under PHP 5.6 with strict warnings enabled

## Expected behavior and actual behavior

Following the steps above, this warning is thrown:
![file_input_warning](https://user-images.githubusercontent.com/2111711/45216284-4fe94800-b2a0-11e8-90f2-301a5577b11e.png)

This is not the case using at least PHP 7.0, or even disabling strict warnings, but there can be (and there are, in fact) hosts where we cannot turn off the warnings even if we want to, so it would still be great to fix this.

## Environment

Libraries

- yii2-krajee-base version: 1.9.4
- yii2-widget-fileinput version: 1.0.6

It seems to me that this needs to be fixed in this extension, and not in yii2-krajee-base, I hope I am correct in opening the issue here.

**Comment by cshehadi** [comment]
+1

**Comment by kartik-v** [comment]
Update to latest release and let know

**Comment by gyula-szabo** [comment]
It is now:
> kartik\base\InputWidget and kartik\base\TranslationTrait define the same property ($i18n) in the composition of kartik\file\FileInput. This might be incompatible, to improve maintainability consider using accessor methods in traits instead. Class was composed

Both InputWidget and FileInput use TranslationTrait. Looks like PHP doesn't like this duplication. I removed the `use TranslationTrait;` line from FileInput to test the theory and it started working again.

**Comment by kartik-v** [comment]
Fixed

**Comment by rklvnoe** [comment]
The row with use TranslationTrait is still in the repositorty?
I still geht the error.

**Comment by kartik-v** [comment]
Not sure what you are checking. Latest release is v1.0.7 and you can cross check [the latest updated code for FileInput](https://github.com/kartik-v/yii2-widget-fileinput/blob/master/src/FileInput.php).

**Comment by amonline** [comment]
The line still exists in v.1.0.7: [](https://github.com/kartik-v/yii2-widget-fileinput/blob/v1.0.7/src/FileInput.php)

**Comment by amonline** [comment]
The line still exists in v1.0.7 
[https://github.com/kartik-v/yii2-widget-fileinput/blob/v1.0.7/src/FileInput.php](https://github.com/kartik-v/yii2-widget-fileinput/blob/v1.0.7/src/FileInput.php)
